### ISSUE TITLE
[REDIS] include support for Sentinel configuration.

### ISSUE THREAD

**Issue by marcelolemes** [jakartaee/nosql#177]
**Description**

As a:

- [ ] Application user/user of the configuration itself
- [X] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

Have the possibility of using functionality (sentinel-client) to consume a Redis high availability arrangement

Source: https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/

**Comment by dearrudam** [comment]
@marcelolemes, thank you for your contribution!!! 

IMHO I think this kind of feature focused on a specific vendor, like Redis, should be managed by implementations instead of the specification like Jakarta NoSQL, like [Eclipse JNoSQL](https://github.com/eclipse/jnosql) ... Eclipse JNoSQL already supports Redis as a NoSQL Key-value family database, so your proposal should fit better there!

**Comment by otaviojava** [comment]
That makes sense.
How about we do some test at the redis implementation?
https://github.com/eclipse/jnosql-databases/tree/main/jnosql-redis

**Comment by marcelolemes** [comment]
@otaviojava 
It seems like a good idea, do you think it's better to recreate this issue there?

**Comment by otaviojava** [comment]
@marcelolemes yes, please do it here:
https://github.com/eclipse/jnosql

**Comment by marcelolemes** [comment]
https://github.com/eclipse/jnosql/issues/534
Reopened like suggested above
